# Generated by Django 5.0.14 on 2025-09-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_stock'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_venta', to='productos.producto'),
        ),
    ]
