# Generated by Django 5.0.14 on 2025-10-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_lineaventa_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='condicion_pago',
            field=models.CharField(default='Contado', help_text='Ej: Contado, 30 días, 60 días', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_ultimo_recordatorio',
            field=models.DateField(blank=True, help_text='Última vez que se envió recordatorio', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha límite para el pago', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones_cobro',
            field=models.TextField(blank=True, help_text='Notas sobre el estado de cobranza'),
        ),
    ]
