# Generated by Django 5.0.14 on 2025-10-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_condicion_pago_venta_fecha_ultimo_recordatorio_and_more'),
    ]

    operations = [
    ]
