# Generated by Django 5.0.14 on 2025-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20251002_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='condicion_pago',
            field=models.CharField(blank=True, default='Contado', help_text='Ej: Contado, 30 días, 60 días', max_length=50, null=True),
        ),
    ]
