# Generated by Django 5.0.14 on 2025-10-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_venta_condicion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='observaciones_cobro',
            field=models.TextField(blank=True, default='', help_text='Notas sobre el estado de cobranza'),
        ),
    ]
