# Generated by Django 5.0.14 on 2025-10-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_venta_observaciones_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='incluye_iva',
            field=models.BooleanField(default=False, help_text='Si está marcado, se aplica 21% de IVA'),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto del IVA (21%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto sin IVA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + IVA', max_digits=12),
        ),
    ]
