# Generated by Django 5.0.14 on 2025-10-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_incluye_iva_venta_iva_monto_venta_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaventa',
            name='cantidad_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cantidad en kilogramos (para facturación)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lineaventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Cantidad en unidades (para descontar stock)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lineaventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio por kilogramo', max_digits=12),
        ),
    ]
