# Generated by Django 5.0.14 on 2025-12-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_add_cantidad_kg_linea_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total pagado de esta factura', max_digits=12),
        ),
    ]
