# Generated by Django 5.0.14 on 2026-01-22 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_venta_monto_pagado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(db_index=True, default=False, help_text='Marca si la venta fue anulada/deshecha'),
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que anuló la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se anuló la venta', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.CharField(blank=True, help_text='Motivo de la anulación', max_length=255),
        ),
    ]
