# Generated by Django 5.0.14 on 2026-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_add_anulacion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada Completamente')], db_index=True, default='PENDIENTE', help_text='Estado de pago de la factura', max_length=20),
        ),
    ]
