# Generated by Django 5.0.14 on 2025-10-28 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Nombre legal completo de la empresa', max_length=200, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, help_text='Nombre comercial de la empresa', max_length=200, verbose_name='Nombre de Fantasía')),
                ('cuit', models.CharField(help_text='XX-XXXXXXXX-X', max_length=13, verbose_name='CUIT')),
                ('condicion_iva', models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributo', 'Monotributo'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor Final')], default='responsable_inscripto', max_length=50, verbose_name='Condición ante IVA')),
                ('inicio_actividades', models.DateField(blank=True, null=True, verbose_name='Inicio de Actividades')),
                ('domicilio_fiscal', models.CharField(max_length=200, verbose_name='Domicilio Fiscal')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('punto_venta', models.IntegerField(default=1, help_text='Punto de venta para facturación electrónica', verbose_name='Punto de Venta')),
                ('certificado_afip', models.FileField(blank=True, help_text='Archivo .crt del certificado digital', null=True, upload_to='certificados/', verbose_name='Certificado AFIP')),
                ('clave_privada_afip', models.FileField(blank=True, help_text='Archivo .key de la clave privada', null=True, upload_to='certificados/', verbose_name='Clave Privada AFIP')),
                ('logo', models.ImageField(blank=True, help_text='Logo para documentos y sistema', null=True, upload_to='empresa/', verbose_name='Logo de la Empresa')),
                ('pie_remito', models.TextField(blank=True, help_text='Texto que aparece al pie de los remitos', verbose_name='Pie de Remito')),
                ('pie_factura', models.TextField(blank=True, help_text='Texto que aparece al pie de las facturas', verbose_name='Pie de Factura')),
                ('banco_nombre', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('banco_cbu', models.CharField(blank=True, max_length=22, verbose_name='CBU')),
                ('banco_alias', models.CharField(blank=True, max_length=50, verbose_name='Alias CBU')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
