# Generated by Django 5.0.14 on 2025-10-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='cai',
            field=models.CharField(blank=True, help_text='Código de Autorización de Impresión', max_length=50, verbose_name='CAI'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='cai_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del CAI', null=True, verbose_name='Vencimiento CAI'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='ingresos_brutos',
            field=models.CharField(blank=True, help_text='Número de Ingresos Brutos', max_length=50, verbose_name='Ingresos Brutos'),
        ),
    ]
