# Generated by Django 5.0.14 on 2025-10-30 00:46

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracionempresa_cai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionempresa',
            name='banco_cbu',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='CBU bancario (encriptado)', verbose_name='CBU'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='cai',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Código de Autorización de Impresión (encriptado)', verbose_name='CAI'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='clave_privada_afip',
            field=models.FileField(blank=True, help_text='Archivo .key de la clave privada (proteger con permisos del sistema)', null=True, upload_to='certificados/', verbose_name='Clave Privada AFIP'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='ingresos_brutos',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Número de Ingresos Brutos (encriptado)', verbose_name='Ingresos Brutos'),
        ),
    ]
