# Generated by Django 5.0.14 on 2025-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
