# Generated by Django 5.0.14 on 2025-10-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_add_missing_sucursal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_principal',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_fiscal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='localidad_fiscal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones generales del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_principal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sucursalcliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
