# Generated by Django 5.0.14 on 2025-10-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_correo_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_fantasia'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='sucursalcliente',
            options={'ordering': ['cliente__nombre_fantasia', 'nombre_sucursal'], 'verbose_name': 'Sucursal de Cliente', 'verbose_name_plural': 'Sucursales de Cliente'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_fantasia',
            field=models.CharField(blank=True, default='', help_text='Nombre comercial o de fantasía del cliente', max_length=200, verbose_name='Nombre de Fantasía'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, default='', help_text='Razón social legal (opcional, para facturas/remitos)', max_length=200, verbose_name='Razón Social'),
        ),
    ]
