# Generated by Django 5.0.14 on 2025-10-30 01:46

from django.db import migrations


def copy_razon_social_to_nombre_fantasia(apps, schema_editor):
    """Copiar razon_social a nombre_fantasia para registros existentes"""
    Cliente = apps.get_model('clientes', 'Cliente')
    for cliente in Cliente.objects.all():
        if not cliente.nombre_fantasia and cliente.razon_social:
            cliente.nombre_fantasia = cliente.razon_social
            cliente.save(update_fields=['nombre_fantasia'])


def reverse_copy(apps, schema_editor):
    """Reversión: copiar nombre_fantasia de vuelta a razon_social"""
    Cliente = apps.get_model('clientes', 'Cliente')
    for cliente in Cliente.objects.all():
        if cliente.nombre_fantasia and not cliente.razon_social:
            cliente.razon_social = cliente.nombre_fantasia
            cliente.save(update_fields=['razon_social'])


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_options_alter_sucursalcliente_options_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_razon_social_to_nombre_fantasia, reverse_copy),
    ]
