# Generated by Django 5.0.14 on 2025-10-02 16:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0004_materiaprima_stock_minimo'),
        ('finanzas_reportes', '0007_configuracionafip_facturaelectronica_and_more'),
        ('ventas', '0003_venta_condicion_pago_venta_fecha_ultimo_recordatorio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('concepto', models.TextField()),
                ('procesado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_contables', to='compras.compra')),
                ('movimiento_financiero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_contables', to='finanzas_reportes.movimientofinanciero')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_contables', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_activo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_pasivo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_patrimonio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance General',
                'verbose_name_plural': 'Balances Generales',
                'ordering': ['-fecha_corte'],
                'unique_together': {('fecha_corte',)},
            },
        ),
        migrations.CreateModel(
            name='EstadoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_costos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilidad_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Resultados',
                'verbose_name_plural': 'Estados de Resultados',
                'ordering': ['-fecha_hasta'],
                'unique_together': {('fecha_desde', 'fecha_hasta')},
            },
        ),
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio Neto'), ('INGRESO', 'Ingresos'), ('GASTO', 'Gastos'), ('COSTO', 'Costos')], max_length=20)),
                ('subtipo_cuenta', models.CharField(choices=[('ACTIVO_CORRIENTE', 'Activo Corriente'), ('ACTIVO_NO_CORRIENTE', 'Activo No Corriente'), ('PASIVO_CORRIENTE', 'Pasivo Corriente'), ('PASIVO_NO_CORRIENTE', 'Pasivo No Corriente'), ('CAPITAL', 'Capital'), ('RESULTADOS', 'Resultados'), ('VENTAS', 'Ventas'), ('OTROS_INGRESOS', 'Otros Ingresos'), ('GASTOS_OPERATIVOS', 'Gastos Operativos'), ('GASTOS_FINANCIEROS', 'Gastos Financieros'), ('COSTO_VENTAS', 'Costo de Ventas')], max_length=30)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('acepta_movimientos', models.BooleanField(default=True, help_text='Si puede recibir asientos contables directamente')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='contabilidad.plancuentas')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsientoContableDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('detalle', models.CharField(blank=True, max_length=500)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.plancuentas')),
            ],
            options={
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Detalles de Asientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoResultadosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.estadoresultados')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.plancuentas')),
            ],
            options={
                'ordering': ['cuenta__codigo'],
                'unique_together': {('estado', 'cuenta')},
            },
        ),
        migrations.CreateModel(
            name='BalanceGeneralDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.balancegeneral')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.plancuentas')),
            ],
            options={
                'ordering': ['cuenta__codigo'],
                'unique_together': {('balance', 'cuenta')},
            },
        ),
    ]
