# Generated by Django 5.0.14 on 2025-10-02 09:10

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0004_materiaprima_stock_minimo'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('productos', '0003_producto_stock_minimo'),
        ('ventas', '0003_venta_condicion_pago_venta_fecha_ultimo_recordatorio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tipo_ajuste', models.CharField(choices=[('FISICO', 'Inventario Físico'), ('CORRECCION', 'Corrección de Error'), ('MERMA', 'Merma/Deterioro'), ('ROBO', 'Robo/Pérdida'), ('ENTRADA_INICIAL', 'Entrada Inicial')], max_length=20)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('procesado', models.BooleanField(default=False)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('fecha_inicio_planificada', models.DateField()),
                ('fecha_fin_planificada', models.DateField()),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('cantidad_planificada', models.DecimalField(decimal_places=3, max_digits=15)),
                ('cantidad_producida', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_PROCESO', 'En Proceso'), ('TERMINADA', 'Terminada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', max_length=20)),
                ('costo_materias_primas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('costo_gastos_generales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descripcion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='productos.producto')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-fecha_creacion', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_DEVOLUCION', 'Entrada por Devolución'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('ENTRADA_INICIAL', 'Entrada Inicial'), ('ENTRADA_PRODUCCION', 'Entrada por Producción'), ('SALIDA_VENTA', 'Salida por Venta'), ('SALIDA_DEVOLUCION', 'Salida por Devolución'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('SALIDA_PRODUCCION', 'Salida por Producción'), ('SALIDA_MERMA', 'Salida por Merma'), ('SALIDA_ROBO', 'Salida por Robo/Pérdida')], max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('cantidad_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('cantidad_nueva', models.DecimalField(decimal_places=3, max_digits=15)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, help_text='Costo unitario del producto en este movimiento', max_digits=15, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('motivo', models.TextField(blank=True, help_text='Explicación del movimiento')),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ajuste_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='inventario.ajusteinventario')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='compras.compra')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ventas.venta')),
                ('orden_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='inventario.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_planificada', models.DecimalField(decimal_places=3, help_text='Cantidad planificada según receta', max_digits=15)),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad realmente consumida', max_digits=15)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('costo_total_planificado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_total_real', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consumido', models.BooleanField(default=False)),
                ('fecha_consumo', models.DateTimeField(blank=True, null=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_produccion', to='compras.materiaprima')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_materia_prima', to='inventario.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Consumo de Materia Prima',
                'verbose_name_plural': 'Consumos de Materia Prima',
            },
        ),
        migrations.CreateModel(
            name='ValorizacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('lote_entrada', models.CharField(blank=True, max_length=100)),
                ('fecha_entrada', models.DateTimeField()),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, max_digits=15)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, max_digits=15)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('costo_total_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_total_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('movimiento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_valorizacion', to='inventario.movimientostock')),
            ],
            options={
                'verbose_name': 'Lote de Valorización',
                'verbose_name_plural': 'Lotes de Valorización',
                'ordering': ['fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='AjusteInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad_sistema', models.DecimalField(decimal_places=3, help_text='Cantidad según el sistema', max_digits=15)),
                ('cantidad_fisica', models.DecimalField(decimal_places=3, help_text='Cantidad contada físicamente', max_digits=15)),
                ('diferencia', models.DecimalField(decimal_places=3, help_text='Diferencia (física - sistema)', max_digits=15)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('costo_total_diferencia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observaciones', models.TextField(blank=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ajusteinventario')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Detalle de Ajuste',
                'verbose_name_plural': 'Detalles de Ajuste',
                'unique_together': {('ajuste', 'content_type', 'object_id')},
            },
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['fecha'], name='inventario__fecha_87302d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['tipo_movimiento'], name='inventario__tipo_mo_be30ab_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['content_type', 'object_id'], name='inventario__content_2fec4b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['venta'], name='inventario__venta_i_ea5e00_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['compra'], name='inventario__compra__3ecb4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consumomateriaprima',
            unique_together={('orden_produccion', 'materia_prima')},
        ),
        migrations.AddIndex(
            model_name='valorizacioninventario',
            index=models.Index(fields=['content_type', 'object_id'], name='inventario__content_1943eb_idx'),
        ),
        migrations.AddIndex(
            model_name='valorizacioninventario',
            index=models.Index(fields=['fecha_entrada'], name='inventario__fecha_e_e1c631_idx'),
        ),
        migrations.AddIndex(
            model_name='valorizacioninventario',
            index=models.Index(fields=['activo'], name='inventario__activo_342775_idx'),
        ),
    ]
