# Generated by Django 5.0.14 on 2025-09-30 23:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cantidad mínima para generar alerta de stock bajo', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
