# Generated by Django 5.0.14 on 2025-10-16 22:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('u', 'Unidades'), ('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('m', 'Metros'), ('cm', 'Centímetros')], default='u', help_text='Unidad de medida para el stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Cantidad mínima para generar alerta de stock bajo', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
