# Generated by Django 5.0.14 on 2025-10-16 22:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_unidad_medida_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Stock en kilogramos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Cantidad mínima de kg para generar alerta de stock bajo', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Stock en unidades', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cantidad mínima de unidades para generar alerta de stock bajo', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
