# Generated by Django 5.0.14 on 2025-09-27 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0004_movimientofinanciero_origen_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SERVICIO', 'Servicio'), ('GASTOS_VARIOS', 'Gastos varios'), ('IMPUESTO', 'Impuesto'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('PAGO_EMPLEADO', 'Pago empleado')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='proveedores.proveedor')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
