# Generated by Django 5.0.14 on 2025-10-01 18:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0005_alter_movimientofinanciero_origen_pagoproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('CORRIENTE', 'Cuenta Corriente'), ('AHORRO', 'Caja de Ahorro'), ('PLAZO_FIJO', 'Plazo Fijo')], default='CORRIENTE', max_length=50)),
                ('titular', models.CharField(max_length=100)),
                ('cbu', models.CharField(blank=True, max_length=22)),
                ('alias', models.CharField(blank=True, max_length=20)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
                'ordering': ['banco', 'numero_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='ExtractoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_movimientos', models.IntegerField(default=0)),
                ('procesado', models.BooleanField(default=False)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractos', to='finanzas_reportes.cuentabancaria')),
            ],
            options={
                'verbose_name': 'extracto bancario',
                'verbose_name_plural': 'extractos bancarios',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('debito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conciliado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('extracto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas_reportes.extractobancario')),
                ('movimiento_financiero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_bancario', to='finanzas_reportes.movimientofinanciero')),
            ],
            options={
                'verbose_name': 'movimiento bancario',
                'verbose_name_plural': 'movimientos bancarios',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conciliacion', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('saldo_libro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_banco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='finanzas_reportes.cuentabancaria')),
            ],
            options={
                'verbose_name': 'conciliación bancaria',
                'verbose_name_plural': 'conciliaciones bancarias',
                'ordering': ['-fecha_conciliacion'],
                'unique_together': {('cuenta_bancaria', 'fecha_conciliacion')},
            },
        ),
    ]
