# Generated by Django 5.0.14 on 2025-10-02 01:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0006_cuentabancaria_extractobancario_movimientobancario_and_more'),
        ('ventas', '0002_lineaventa_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAFIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('ambiente', models.CharField(choices=[('testing', 'Homologación'), ('production', 'Producción')], default='testing', max_length=20)),
                ('certificado_path', models.CharField(help_text='Ruta al archivo .crt', max_length=500)),
                ('clave_privada_path', models.CharField(help_text='Ruta al archivo .key', max_length=500)),
                ('punto_venta', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración AFIP',
                'verbose_name_plural': 'configuraciones AFIP',
            },
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('1', 'Factura A'), ('6', 'Factura B'), ('11', 'Factura C'), ('2', 'Nota de Débito A'), ('7', 'Nota de Débito B'), ('12', 'Nota de Débito C'), ('3', 'Nota de Crédito A'), ('8', 'Nota de Crédito B'), ('13', 'Nota de Crédito C')], max_length=2)),
                ('punto_venta', models.IntegerField()),
                ('numero_comprobante', models.IntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cliente_tipo_documento', models.CharField(choices=[('80', 'CUIT'), ('86', 'CUIL'), ('87', 'CDI'), ('89', 'LE'), ('90', 'LC'), ('91', 'CI Extranjera'), ('92', 'En Trámite'), ('93', 'Acta Nacimiento'), ('95', 'CI Buenos Aires'), ('96', 'DNI'), ('94', 'Pasaporte')], default='96', max_length=2)),
                ('cliente_numero_documento', models.CharField(max_length=20)),
                ('cliente_razon_social', models.CharField(max_length=255)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('cliente_domicilio', models.CharField(blank=True, max_length=255)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('importe_otros_tributos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cae', models.CharField(blank=True, help_text='Código de Autorización Electrónico', max_length=14, null=True)),
                ('fecha_vencimiento_cae', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado a AFIP'), ('APROBADO', 'Aprobado por AFIP'), ('RECHAZADO', 'Rechazado por AFIP'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('observaciones_afip', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100)),
                ('configuracion_afip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas_reportes.configuracionafip')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura_electronica', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'factura electrónica',
                'verbose_name_plural': 'facturas electrónicas',
                'ordering': ['-fecha_emision', '-numero_comprobante'],
                'unique_together': {('configuracion_afip', 'tipo_comprobante', 'punto_venta', 'numero_comprobante')},
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('importe_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='finanzas_reportes.facturaelectronica')),
            ],
            options={
                'verbose_name': 'detalle factura electrónica',
                'verbose_name_plural': 'detalles factura electrónica',
            },
        ),
        migrations.CreateModel(
            name='LogAFIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('request_xml', models.TextField(blank=True)),
                ('response_xml', models.TextField(blank=True)),
                ('resultado', models.CharField(choices=[('OK', 'Exitoso'), ('ERROR', 'Error'), ('WARNING', 'Advertencia')], max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('codigo_error', models.CharField(blank=True, max_length=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finanzas_reportes.facturaelectronica')),
            ],
            options={
                'verbose_name': 'log AFIP',
                'verbose_name_plural': 'logs AFIP',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
