# Generated by Django 5.0.14 on 2025-10-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0007_configuracionafip_facturaelectronica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('COBRADO', 'Cobrado'), ('CANCELADO', 'Cancelado')], default='PAGADO', max_length=15),
        ),
    ]
