# Generated by Django 5.0.14 on 2025-10-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0009_cuentas_por_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], help_text='Medio con el que se registró el cobro/pago real', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='medio',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SERVICIO', 'Servicio'), ('GASTOS_VARIOS', 'Gastos varios'), ('IMPUESTO', 'Impuesto'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('PAGO_EMPLEADO', 'Pago empleado'), ('PAGO_PROVEEDOR', 'Pago proveedor')], default='MANUAL', max_length=20),
        ),
    ]
