# Generated by Django 5.0.14 on 2025-10-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0010_movimientofinanciero_medio_pago_pagoproveedor_medio_and_more'),
        ('ventas', '0007_venta_incluye_iva_venta_iva_monto_venta_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocliente',
            name='venta',
            field=models.ForeignKey(blank=True, help_text='Factura/venta asociada a este pago (opcional, para clientes que pagan por factura)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='ventas.venta'),
        ),
    ]
