# Generated by Django 5.0.14 on 2025-10-30 19:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0011_pagocliente_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('PRESENTADO', 'Presentado a AFIP')], default='ABIERTO', max_length=20)),
                ('iva_debito_fiscal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='IVA cobrado en ventas (21%)', max_digits=12)),
                ('iva_credito_fiscal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='IVA pagado en compras (deducible)', max_digits=12)),
                ('saldo_favor_fisco', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Saldo a favor del fisco (débito - crédito si es positivo)', max_digits=12)),
                ('saldo_favor_contribuyente', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Saldo a favor del contribuyente (crédito - débito si es positivo)', max_digits=12)),
                ('fecha_presentacion', models.DateField(blank=True, help_text='Fecha de presentación de la DJ', null=True)),
                ('numero_presentacion', models.CharField(blank=True, help_text='Número de presentación AFIP', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'período IVA',
                'verbose_name_plural': 'períodos IVA',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='PagoIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('VEP', 'Volante Electrónico de Pago (VEP)'), ('DEBITO', 'Débito Automático'), ('COMPENSACION', 'Compensación con saldos a favor')], max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de VEP o comprobante', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('movimiento_financiero', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_iva', to='finanzas_reportes.movimientofinanciero')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas_reportes.periodoiva')),
            ],
            options={
                'verbose_name': 'pago de IVA',
                'verbose_name_plural': 'pagos de IVA',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
