# Generated by Django 5.0.14 on 2026-01-22 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0012_periodoiva_pagoiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocliente',
            name='anulado',
            field=models.BooleanField(db_index=True, default=False, help_text='Marca si el pago fue anulado/deshecho'),
        ),
        migrations.AddField(
            model_name='pagocliente',
            name='anulado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que anuló el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagocliente',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se anuló el pago', null=True),
        ),
    ]
