# Generated by Django 5.0.14 on 2026-01-30 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0013_add_anulacion_fields_pago'),
        ('ventas', '0011_add_payment_allocation_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImputacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_imputado', models.DecimalField(decimal_places=2, help_text='Monto de este pago aplicado a esta factura', max_digits=12)),
                ('fecha_imputacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la imputación')),
                ('revertida', models.BooleanField(db_index=True, default=False, help_text='True si esta imputación fue revertida (undo de pago)')),
                ('fecha_reversion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se revirtió la imputación', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre esta imputación (ej: aplicada automáticamente por FIFO)')),
                ('pago', models.ForeignKey(help_text='Pago que se está aplicando', on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones', to='finanzas_reportes.pagocliente')),
                ('venta', models.ForeignKey(help_text='Factura a la que se aplica el pago', on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Imputación de Pago',
                'verbose_name_plural': 'Imputaciones de Pago',
                'ordering': ['-fecha_imputacion', '-id'],
                'indexes': [models.Index(fields=['venta', 'revertida'], name='idx_venta_activa'), models.Index(fields=['pago', 'revertida'], name='idx_pago_activa'), models.Index(fields=['fecha_imputacion'], name='idx_fecha_imput')],
            },
        ),
        migrations.AddConstraint(
            model_name='imputacionpago',
            constraint=models.CheckConstraint(check=models.Q(('monto_imputado__gt', 0)), name='monto_imputado_positivo'),
        ),
    ]
