# Generated by Django 5.0.14 on 2025-10-02 02:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Mi PyME', help_text='Nombre de la empresa', max_length=200)),
                ('logo_empresa', models.ImageField(blank=True, help_text='Logo de la empresa', null=True, upload_to='logos/')),
                ('max_usuarios', models.PositiveIntegerField(default=10, help_text='Máximo número de usuarios permitidos')),
                ('requiere_cambio_password', models.BooleanField(default=True, help_text='Requiere cambio de contraseña en primer acceso')),
                ('dias_vigencia_password', models.PositiveIntegerField(default=90, help_text='Días de vigencia de las contraseñas')),
                ('intentos_login_max', models.PositiveIntegerField(default=3, help_text='Máximo intentos de login antes de bloquear')),
                ('session_timeout', models.PositiveIntegerField(default=30, help_text='Tiempo de sesión en minutos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nivel_acceso', models.CharField(choices=[('ADMIN_TOTAL', 'Administrador Total'), ('ADMIN_NIVEL_2', 'Administrador Nivel 2'), ('ADMIN_NIVEL_1', 'Administrador Nivel 1')], default='ADMIN_NIVEL_1', help_text='Nivel de acceso del usuario en el sistema', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, help_text='Cargo o puesto del usuario en la empresa', max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Fecha de ingreso del usuario a la empresa', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario está activo en el sistema')),
                ('ultima_actividad', models.DateTimeField(blank=True, help_text='Última vez que el usuario accedió al sistema', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_creacion'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Logs de Acceso',
                'ordering': ['-fecha_acceso'],
            },
        ),
    ]
