# Generated by Django 5.0.14 on 2025-10-06 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacceso',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (puede ser null para intentos fallidos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_acceso', to=settings.AUTH_USER_MODEL),
        ),
    ]
