# Generated by Django 5.0.14 on 2025-10-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_allow_null_usuario_in_logacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Forzar cambio de contraseña en próximo login', verbose_name='Debe cambiar contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se reseteó la contraseña', null=True, verbose_name='Fecha de reset de contraseña'),
        ),
    ]
