# Generated by Django 5.0.14 on 2026-01-22 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('usuarios', '0003_usuario_debe_cambiar_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndoAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE_VENTA', 'Crear Venta'), ('EDIT_VENTA', 'Editar Venta'), ('REGISTER_PAGO_CLIENTE', 'Registrar Pago')], max_length=50, verbose_name='Tipo de Acción')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_state_hash', models.CharField(blank=True, help_text='SHA256 de campos críticos para validar estado', max_length=64, null=True)),
                ('undo_payload', models.JSONField(help_text='Información necesaria para revertir la acción', verbose_name='Datos para Deshacer')),
                ('group_id', models.UUIDField(blank=True, db_index=True, help_text='Agrupa múltiples acciones relacionadas', null=True, verbose_name='ID de Grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('undone_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Deshacer')),
                ('rollback_status', models.JSONField(blank=True, default=dict, help_text='Estado del rollback: steps_completed, error, etc.')),
                ('has_failed_rollback', models.BooleanField(db_index=True, default=False, verbose_name='Rollback Falló')),
                ('description', models.CharField(help_text='Descripción amigable para mostrar en la interfaz', max_length=255, verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undo_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acción Deshacible',
                'verbose_name_plural': 'Acciones Deshacibles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'undone_at', 'created_at'], name='usuarios_un_user_id_0ecece_idx'), models.Index(fields=['group_id'], name='usuarios_un_group_i_f66fc6_idx')],
            },
        ),
    ]
