# Generated by Django 5.0.14 on 2026-01-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_add_undoaction_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undoaction',
            name='action_type',
            field=models.CharField(choices=[('CREATE_VENTA', 'Crear Venta'), ('EDIT_VENTA', 'Editar Venta'), ('REGISTER_PAGO_CLIENTE', 'Registrar Pago'), ('CREATE_COMPRA', 'Crear Compra')], max_length=50, verbose_name='Tipo de Acción'),
        ),
    ]
