# Generated by Django 5.0.14 on 2025-09-29 21:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compralinea_kilaje_compralinea_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('u', 'Unidades'), ('m', 'Metros'), ('cm', 'Centímetros')], default='u', max_length=20)),
                ('stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_promedio', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio promedio ponderado', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'materia prima',
                'verbose_name_plural': 'materias primas',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='compralinea',
            name='kilaje',
        ),
        migrations.RemoveField(
            model_name='compralinea',
            name='producto',
        ),
        migrations.AlterField(
            model_name='compralinea',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compralinea',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.materiaprima'),
        ),
    ]
