# Generated by Django 5.0.14 on 2025-10-03 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_materiaprima_stock_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStockMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_ajuste', models.CharField(choices=[('ENTRADA', 'Entrada (agregar stock)'), ('SALIDA', 'Salida (quitar stock)'), ('CORRECCION', 'Corrección de inventario'), ('MERMA', 'Merma/pérdida'), ('DEVOLUCION', 'Devolución')], default='CORRECCION', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad ajustada (positiva para entrada, negativa para salida)', max_digits=12)),
                ('stock_anterior', models.DecimalField(decimal_places=3, help_text='Stock antes del ajuste', max_digits=12)),
                ('stock_nuevo', models.DecimalField(decimal_places=3, help_text='Stock después del ajuste', max_digits=12)),
                ('motivo', models.CharField(help_text='Motivo del ajuste', max_length=255)),
                ('usuario', models.CharField(blank=True, help_text='Usuario que realizó el ajuste', max_length=100)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_stock', to='compras.materiaprima')),
            ],
            options={
                'verbose_name': 'ajuste de stock',
                'verbose_name_plural': 'ajustes de stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
