# Generated by Django 5.0.14 on 2025-10-03 04:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_ajustestockmateriaprima'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPorProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Cantidad en stock de esta materia prima proveniente de este proveedor', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_promedio', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio promedio ponderado de compras a este proveedor', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ultima_compra', models.DateField(blank=True, help_text='Fecha de la última compra a este proveedor', null=True)),
                ('total_comprado', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Total histórico comprado a este proveedor', max_digits=12)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_por_proveedor', to='compras.materiaprima')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_materias_primas', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'stock por proveedor',
                'verbose_name_plural': 'stock por proveedor',
                'ordering': ['materia_prima__nombre', 'proveedor__nombre'],
                'unique_together': {('materia_prima', 'proveedor')},
            },
        ),
    ]
