# Generated by Django 5.0.14 on 2025-10-03 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_stockporproveedor'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustestockmateriaprima',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor específico afectado por el ajuste (para salidas/consumos)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_stock_materias', to='proveedores.proveedor'),
        ),
    ]
