# Generated by Django 5.0.14 on 2025-10-30 23:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_ajustestockmateriaprima_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='incluye_iva',
            field=models.BooleanField(default=False, help_text='Si está marcado, se aplica 21% de IVA'),
        ),
        migrations.AddField(
            model_name='compra',
            name='iva_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto del IVA (21%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto sin IVA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Subtotal + IVA', max_digits=12),
        ),
    ]
