# Generated by Django 5.0.14 on 2025-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compra_incluye_iva_compra_iva_monto_compra_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
