# Generated by Django 5.0.14 on 2026-01-23 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_allow_null_sku_materia_prima'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='anulada',
            field=models.BooleanField(db_index=True, default=False, help_text='Marca si la compra fue anulada/deshecha'),
        ),
        migrations.AddField(
            model_name='compra',
            name='anulada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que anuló la compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se anuló la compra', null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_anulacion',
            field=models.CharField(blank=True, help_text='Motivo de la anulación', max_length=255),
        ),
    ]
