# Generated by Django 5.0.14 on 2025-09-30 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellidos', 'nombre']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuil',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pagoempleado',
            name='generar_recibo',
            field=models.BooleanField(default=False, help_text='Genera recibo de sueldo'),
        ),
        migrations.AddField(
            model_name='pagoempleado',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagoempleado',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
