# Generated by Django 5.0.14 on 2025-10-03 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_alter_empleado_options_empleado_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pagoempleado',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
